module.exports = {
    containerFull:{
        width:'100%',
        height:'100%',
        backgroundColor:'black',
        alignItems:'center',
        justifyContent:'center',
    },
    logo1:{
        height:70,
        resizeMode:'contain',
        marginBottom:20
    },
    logo2:{
        height:30,
        resizeMode:'contain',
        width:100,
    },
    hr80:{
        width:'80%',
        height:1,
        backgroundColor:'gray',
        marginVertical:10,
    },
    goBack:{
        flexDirection:'row',
        position:'absolute',
        top:50,
        left:20,
        alignItems:'center'
    }, 
    row:{
        flexDirection:'row',
        alignItems:'center',
        marginVertical:10
    },
    icon1:{
      color:'white',
      fontSize:30
    }
}